version: "3"

networks: 
    laravel:

services: 
    nginx:
        image: nginx:1.19.0-alpine
        ports: 
            - "8080:80"
        volumes: 
            - ./src:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks: 
            - laravel
            
    php:
        # image: php:7.2-fpm-alpine
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - "9000:9000"
        volumes: 
            - ./src:/var/www/html
        networks: 
            - laravel
    
    mysql:
        image: mysql:5.7.22
        ports: 
            - "3306:3306"
        volumes: 
            - ./docker/mysql:/var/lib/mysql
        networks: 
            - laravel
        environment: 
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql